config/routes.rb
Sitehunt::Application.routes.draw do

  resources :users

  get 'auth/:provider/callback', to: 'sessions#create',  via: [:post, :get]
  get '/logout', to: 'sessions#destroy',  via: [:post, :get]
  match '/details', to: 'users#details' , via:[:post, :get]

  get "/:username" => "users#show"

  resources :users

  resources :products do
    member do
      put :upvote
      put :comment
      post :commentcreate
    end
  end

  root 'products#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :votes
	has_many :comments
	validates :url, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  has_many :comments

  def to_param
    username
  end
  
  def self.find_with_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid'])
  end

  def self.create_with_omniauth(auth)
    create!(uid: auth['uid'], provider: auth['provider'], username: auth.info['nickname'], image: auth.info['image'], name: auth.info['name'], description: auth.info['description'])
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.nil? ? nil : user.id
  end


  def store_location
     session[:return_to] = request.url if request.get?
  end

  def sign_out
      return unless signed_in?
      self.current_user = nil
  end


  def redirect_unless_signed_in
      unless signed_in?
          store_location
        redirect_to root_url, notice: "Please sign in."
      end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :redirect_unless_signed_in, only: [:create, :destroy]
  
  def index
    @products = Product.all
  end

  def show

  end

  def new
    @product = Product.new
  end

  def create
   @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_url, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @productid = params[:id]
    service = UpvoteService.new(current_user.id, @productid).call
    @vote_number = service
    # VoteQuery.new(product_id: @productid).total_count
    respond_to do |format|
      format.js
    end
  end

  def comment
    @product_id = params[:id]
    @comments = Comment.where(product_id: @product_id)
    respond_to do |format|
      format.js
    end
  end

  def commentcreate
    @comment = Comment.new(title: params['title'], product_id: params['product_id'], user_id: current_user.id )
    @product_id = params[:id]
    @comments = Comment.where(product_id: @product_id)
    respond_to do |format|
      if @comment.save
        format.js
      else
        redirect_to 'root_url'
      end
    end
  end

  def product_params
    params.require(:product).permit(:productname, :url, :description, :date => Date.new)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env['omniauth.auth']
    user = User.find_with_omniauth(auth)
    unless user
     user = User.create_with_omniauth(auth)
     new_user = true
    end
    session[:user_id] = user.id
    current_user = user
    if new_user
    	redirect_to '/details'
    else
    	redirect_to '/'
    end
  end

  def destroy
  	sign_out
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_username(params[:username]) if params[:username]
    @user = User.find_by_id(params[:id]) if params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def details
    if params[:email]
      email = params[:email]
      @user = current_user
      @user.update(email: email)
      redirect_to '/'
    end
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = (User.find_by(username: params[:username] || User.find(params[:id])))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:provider, :uid, :name, :image, :username, :description, :token, :secret)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechTrend</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="col-lg-12 col-md-12 col-sm-12">
	<div class="container  col-md-offset-1 col-md-4">
		<a href="/"><h1 class="col-md-offset-1 site-title" >TechTrend</h1></a> 
		<p class="subtitle">The Best New Indian Products Everyday</p>
	</div>
	<div class="links">
		<% if signed_in? %>
			<%= link_to 'Add a Product', new_product_path, class: "btn"%>
			<%=link_to 'Logout', '/logout', class: "btn" %>
		<% else %>
			<%= link_to 'Login With Twitter', '/auth/twitter', class: "btn btn-default" %>
		<%end %>
	</div>
</header>

<%= yield %>

</body>
</html>

app/views/products/_comments.html.erb
<% product = Product.find(@product_id) %>

<div class="who-posted">
<%= link_to(image_tag(product.user.image, class: "post-user-comment-image"), product.user.username) %>  Posted By <%= product.user.username %>
</div>

<div class="product-name-comment-section">
	<h2 class="red-color"><%= product.productname %></h2>
	<h4><%= product.description %></h4>
</div>

<h2 class="comment-count"><%= @comments.count %> Comments</h2>
<hr>

<!-- Add comment -->
<% if signed_in? %>
	<div class="row all-comments">
		<%= form_tag({ :controller => :products, :action => :commentcreate }, { :remote => true }) do%>

			<div class="comment-form ">
					<%= label_tag :title, 'Comment:', class: "col-sm-2 control-label" %>
		      <div class="">
		       <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "Your Comment" %>
		      </div>
		      <%= hidden_field_tag :product_id, params[:product_id] = product.id %>
		  </div>
		<% end %>
		<br>
	</div>
<% end %>

<div>
	<% @comments.each do |comment| %>
	<div class="each-comment">
		<%= link_to(image_tag(comment.user.image, class: "post-user-comment-image"), product.user.username) %>
		<span class="red-color"><%= comment.user.username %></span>
		<p class="comment-title" style="line-height: 2px"><%= comment.title %></p>
		<hr style="margin-top: 5px; margin-bottom: 5px;">
	</div>
	<%end %>
</div>

app/views/products/comment.js.erb
$('.comments').removeClass('hidden-comments');
$('.right-half').html("<%= escape_javascript render(file: '/products/_comments.html.erb', comments: @comments) %>");

app/views/products/commentcreate.js.erb
$('.comments').removeClass('hidden-comments');
$('.right-half').html("<%= escape_javascript render(file: '/products/_comments.html.erb', comments: @comments) %>");

app/views/products/index.html.erb
<% last = Product.last.id %>
<% @productyesterday = Product.find([1,2]).reverse %>
<% @products = Product.limit(100).offset(2).reverse %>
<%= content_tag(:span, notice, class: 'col-md-offset-5 notice') if notice %>
<div class= "container product-listing">
	<div class="wrapper col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10 col-sm-12">
		<div class="search-box">
			
		</div>
		<div class= "post-container">
			<div class="posts-today">
				<h2 style="margin-bottom:27px;"> TODAY </h2>
				<% @products.each do |product| %>
						<div class="post">
								<div class="upvote" id=<%=product.id%>>
								<%= link_to "", upvote_product_path(product.id), remote: true, :method => 'put', class: "upvote-btn" %>
									<span class="vote-count"><%= Vote.find_by_sql("SELECT * From votes where product_id = #{product.id}").count %></span>
								</div> 
							
							<div class="url">
								<span class="productname"><%= link_to product.productname, "http://#{product.url}", target: "black" %></span>
								<span class="producttagline"><%= product.description %></span>
							</div>
							<span class="post-user-image">
								<%= link_to(image_tag(product.user.image, class: "post-user-image"), product.user.username) %>
							</span>
							<%= link_to 'comments', comment_product_path(product.id), remote: true, method: 'put' %>
						</div>
				<% end %>
			</div>
		</div>
		<div class= "post-container">
			<div class="posts-today"><h2> YESTERDAY </h2>
				<% @productyesterday.each do |product| %>
						<div class="post">
								<div class="upvote" id=<%=product.id%>>
								<%= link_to "", upvote_product_path(product.id), remote: true, :method => 'put', class: "upvote-btn" %>
									<span class="vote-count"><%= Vote.find_by_sql("SELECT * From votes where product_id = #{product.id}").count %></span>
								</div> 
							
							<div class="url">
								<span class="productname"><%= link_to product.productname, "http://#{product.url}", target: "black" %></span>
								<span class="producttagline"><%= product.description %></span>
							</div>
							<span class="post-user-image">
								<%= link_to(image_tag(product.user.image, class: "post-user-image"), product.user.username) %>
							</span>
							<%= link_to 'comments', comment_product_path(product.id), remote: true, method: 'put' %>
						</div>
				<% end %>
			</div>
		</div>
	</div>
</div>


<div class="comments hidden-comments">
	<div class="left-half">

	</div>
	<div class="right-half">
		
	</div>
</div>

<script>
$('.post').click(function(){
	var id = $(this).find('upvote').attr("id");
   $.ajax({
   		 type: "",
      url: "",
     
   });
});

$('.left-half').click(function(){
	$('.comments').addClass('hidden-comments');
});
</script>

app/views/products/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <div class="productaddform">
  <div class="productform-box col-md-offset-3">
      <%= form_for(@product) do |f| %>
      <p> Post a Product</p>
       <div class="field">
          <%= f.label :productname, class: "inputfieldname"  %><br>
          <%= f.text_field :productname, class: "inputfield" %>
        </div>
        <div class="field">
          <%= f.label :description, class: "inputfieldname" %><br>
          <%= f.text_field :description, class: "inputfield"  %>
        </div>
        <div class="field">
          <%= f.label :url, class: "inputfieldname" %><br>
          <%= f.text_field :url, class: "inputfield"  %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
</div>
</div>

app/views/products/upvote.js.erb
$('#<%= @productid %> .vote-count').html('<%= @vote_number %>');
$('#<%= @productid %> .upvote-btn').addClass("voted");

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field ">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/details.html.erb
<div class="container detail-form-container">
<div class="col-md-offset-3 col-md-6 details-form">
<%= form_tag({ controller: 'users', action: 'details' }, :method => "post", id: "email-form", class: "col-md-12 detailsaddform") do %>
	<p>Please Enter your Email</p>
  <%= text_field_tag :email, params[:email], placeholder: "Your Email-id", class: "inputfield" %>
  <%= submit_tag "Save", :name => nil, class:"submit" %>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>Uid</th>
      <th>Name</th>
      <th>Image</th>
      <th>Username</th>
      <th>Description</th>
      <th>Token</th>
      <th>Secret</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= user.name %></td>
        <td><%= user.image %></td>
        <td><%= user.username %></td>
        <td><%= user.description %></td>
        <td><%= user.token %></td>
        <td><%= user.secret %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-offset-3 col-md-6 user-info" style="align-text: center; background-color:#fcf5e2;">

  <%= link_to(image_tag(@user.image, class: "show-user-image")) %>

  <%= @user.name %><br>

  <strong>Twitter Username:</strong>
  <%= @user.username %>


<br>
</div>